### Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

### Data Collection

In [2]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\seattle-weather.csv")
df


date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

### Data Preprocessing

In [3]:
df.drop(columns=["date"], inplace=True)
df

precipitation  temp_max  temp_min  wind  weather
0               0.0      12.8       5.0   4.7  drizzle
1              10.9      10.6       2.8   4.5     rain
2               0.8      11.7       7.2   2.3     rain
3              20.3      12.2       5.6   4.7     rain
4               1.3       8.9       2.8   6.1     rain
...             ...       ...       ...   ...      ...
1456            8.6       4.4       1.7   2.9     rain
1457            1.5       5.0       1.7   1.3     rain
1458            0.0       7.2       0.6   2.6      fog
1459            0.0       5.6      -1.0   3.4      sun
1460            0.0       5.6      -2.1   3.5      sun

[1461 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   precipitation  1461 non-null   float64
 1   temp_max       1461 non-null   float64
 2   temp_min       1461 non-null   float64
 3   wind           1461 non-null   float64
 4   weather        1461 non-null   object 
dtypes: float64(4), object(1)
memory usage: 57.2+ KB


In [5]:
df.describe()

precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [6]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1456    False
1457    False
1458    False
1459    False
1460    False
Length: 1461, dtype: bool

In [7]:
df.duplicated().sum()

np.int64(8)

In [8]:
df.isnull().sum()

precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder, StandardScaler


### Encoding using Label Encoder

In [10]:
for col in df.select_dtypes(include=[object]).columns:
    le=LabelEncoder()
    df[col]=le.fit_transform(df[col])

In [11]:
df.head()

precipitation  temp_max  temp_min  wind  weather
0            0.0      12.8       5.0   4.7        0
1           10.9      10.6       2.8   4.5        2
2            0.8      11.7       7.2   2.3        2
3           20.3      12.2       5.6   4.7        2
4            1.3       8.9       2.8   6.1        2

### Using Standard Scaler to scale values

In [12]:
scaler=StandardScaler()
scaler.fit_transform(df)

array([[-0.45364986, -0.49529914, -0.64421175,  1.01497975, -2.31090504],
       [ 1.17859791, -0.79473121, -1.08234662,  0.87583314, -0.63160523],
       [-0.33385186, -0.64501518, -0.20607688, -0.65477956, -0.63160523],
       ...,
       [-0.45364986, -1.25748987, -1.52048149, -0.44605965, -1.47125513],
       [-0.45364986, -1.47525865, -1.83912504,  0.11052679,  1.04769457],
       [-0.45364986, -1.47525865, -2.05819247,  0.18010009,  1.04769457]],
      shape=(1461, 5))

### Feature Selection

In [13]:
x=df.drop("weather",axis=1)
x

precipitation  temp_max  temp_min  wind
0               0.0      12.8       5.0   4.7
1              10.9      10.6       2.8   4.5
2               0.8      11.7       7.2   2.3
3              20.3      12.2       5.6   4.7
4               1.3       8.9       2.8   6.1
...             ...       ...       ...   ...
1456            8.6       4.4       1.7   2.9
1457            1.5       5.0       1.7   1.3
1458            0.0       7.2       0.6   2.6
1459            0.0       5.6      -1.0   3.4
1460            0.0       5.6      -2.1   3.5

[1461 rows x 4 columns]

In [14]:
y=df["weather"]
y

0       0
1       2
2       2
3       2
4       2
       ..
1456    2
1457    2
1458    1
1459    4
1460    4
Name: weather, Length: 1461, dtype: int64

### Splitting data for training and testing purpose

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

### Importing dependencies for Deep Learning Model

In [16]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

### Using Sequential to prepare ANN

In [17]:
model=Sequential()
model.add(Dense(10,activation="relu",input_dim=4))
model.add(Dense(10,activation="relu"))
model.add(Dense(10,activation="relu"))
model.add(Dense(10,activation="relu"))
model.add(Dense(10,activation="relu"))
model.add(Dense(5,activation="softmax"))          

c:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Model Summary

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │            55 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 545 (2.13 KB)

 Trainable params: 545 (2.13 KB)

 Non-trainable params: 0 (0.00 B)

### Model Training

In [ ]:
model.compile(optimizer="Adam",loss="sparse_categorical_crossentropy")

In [20]:
model.fit(x_train,y_train,epochs=50)


Epoch 1/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 3.3898
Epoch 2/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.2379
Epoch 3/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9736
Epoch 4/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8800
Epoch 5/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8410
Epoch 6/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8086
Epoch 7/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7888
Epoch 8/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7781
Epoch 9/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7497
Epoch 10/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7372
Epoch 11/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7265
Epoch 12/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7225
Epoch 13/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7074
Epoch 14/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6952
Epoch 15/50
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6866
Epoch 16/50
37/37 

In [21]:
model.save("weather_model.h5", save_format="h5", include_optimizer=False)


### Predicting using x_test

In [22]:
y_pred=model.predict(x_test)
y_pred

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[3.70106101e-02, 6.10182919e-02, 2.41622869e-02, 7.60267285e-05,
        8.77732754e-01],
       [1.70313882e-07, 2.83175677e-06, 9.99875069e-01, 1.06467705e-04,
        1.54135123e-05],
       [7.02762976e-02, 8.72931704e-02, 2.23658368e-01, 1.66158210e-02,
        6.02156341e-01],
       ...,
       [7.28869811e-02, 1.08833820e-01, 9.69492272e-02, 2.19849194e-03,
        7.19131589e-01],
       [2.47539333e-06, 2.90994831e-05, 9.99424815e-01, 3.83140956e-04,
        1.60555646e-04],
       [3.81866880e-02, 5.18152751e-02, 4.16017808e-02, 3.14452191e-04,
        8.68081748e-01]], shape=(293, 5), dtype=float32)

### Using argmax for turning continuous outputs into final predicted class labels

In [23]:
y_pred_int = np.argmax(y_pred, axis=1)
y_pred_int

array([4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 4, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 4, 2, 4, 2, 2, 4, 2, 4, 2, 4, 2, 4, 4, 4,
       2, 4, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 2, 4, 4, 4,
       4, 2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 4, 4, 2, 4, 2, 4, 4, 2, 4, 2,
       2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4,
       2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 2,
       4, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2,
       2, 2, 2, 4, 4, 2, 4, 2, 2, 4, 2, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 4, 2, 4, 2, 4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 4, 2, 2,
       4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2,
       4, 4, 2, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 4, 4, 4, 4,
       2, 4, 4, 2, 4, 2, 4])

In [24]:
y_test.shape


(293,)

In [25]:
y_pred_int.shape

(293,)

### Model Evaluation

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_int)

0.8225255972696246

### Making prediction on new data

In [27]:
new_data = np.array([[0.5, 25,22,15]])
y_pred_new = model.predict(new_data)        
y_pred_int_new = np.argmax(y_pred_new, axis=1)   
y_pred_label = le.inverse_transform(y_pred_int_new)   
print("Predicted Weather:", y_pred_label[0])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
Predicted Weather: rain
